[features]
seeds = false
skip-lint = false

[programs.localnet]
expense_program = "rzMxNuut6R34aFgt8NY9hj3SoRB37iszrsSqZR2DSnB"

[programs.devnet]
expense_program = "rzMxNuut6R34aFgt8NY9hj3SoRB37iszrsSqZR2DSnB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
